# In Alacritty, background opacity is set via the alpha channel of the background color.
# You might define your own background color with the desired opacity.
[window]
# background = "0x000000CC"  # 0xCC is 80% opacity in hexadecimal (204/255 ≈ 0.8)
# opacity = 0.90

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Extra Bold" }
# If you have a distinct italic font, specify it; otherwise you can reuse the normal font.
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Extra Bold Italic" }
size = 12.0
# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

# rose pine moon config. very pretty!
